class AddCryptoCurrencies < ActiveRecord::Migration[5.1]
  CURRENCIES = [
    {symbol: 'ADA',   name: 'ADA'},
    {symbol: 'ADC',   name: 'ADC'},
    {symbol: 'AEON',  name: 'Aeon'},
    {symbol: 'ARDR',  name: 'ARDR'},
    {symbol: 'ARK',   name: 'ARK'},
    {symbol: 'REP',   name: 'Augur'},
    {symbol: 'AUR',   name: 'Auroracoin'},
    {symbol: 'BAT',   name: 'BAT'},
    {symbol: 'BTA',   name: 'Bata'},
    {symbol: 'BAY',   name: 'BAY'},
    {symbol: 'BTC',   name: 'Bitcoin'},
    {symbol: 'BCH',   name: 'Bitcoin Cash'},
    {symbol: 'BTCD',  name: 'BitcoinDark'},
    {symbol: 'BTM',   name: 'Bitmark'},
    {symbol: 'BSD',   name: 'BitSend'},
    {symbol: 'BTS',   name: 'BitShares'},
    {symbol: 'SWIFT', name: 'BitSwift'},
    {symbol: 'BRK',   name: 'BRK'},
    {symbol: 'BRX',   name: 'BRX'},
    {symbol: 'GBYTE', name: 'Byteball'},
    {symbol: 'BCN',   name: 'Bytecoin'},
    {symbol: 'CLAM',  name: 'Clams'},
    {symbol: 'CLOAK', name: 'Cloakcoin'},
    {symbol: 'XCP',   name: 'Counterparty'},
    {symbol: 'DGD',   name: 'DarkGoldCoin'},
    {symbol: 'DASH',  name: 'Dash'},
    {symbol: 'DCT',   name: 'DCT'},
    {symbol: 'DCR',   name: 'Decred'},
    {symbol: 'DMD',   name: 'Diamond'},
    {symbol: 'DGB',   name: 'Digibyte'},
    {symbol: 'NOTE',  name: 'DNotes'},
    {symbol: 'DOGE',  name: 'Dogecoin'},
    {symbol: 'EMC',   name: 'Emercoin'},
    {symbol: 'EOS',   name: 'EOS'},
    {symbol: 'ERC',   name: 'ERC'},
    {symbol: 'ETH',   name: 'Ethereum'},
    {symbol: 'ETC',   name: 'Ethereum Classic'},
    {symbol: 'FCT',   name: 'Factom'},
    {symbol: 'FTC',   name: 'Feathercoin'},
    {symbol: 'FLO',   name: 'Florincoin'},
    {symbol: 'FRK',   name: 'Franko'},
    {symbol: 'GAME',  name: 'GameCredits'},
    {symbol: 'GNO',   name: 'GNO'},
    {symbol: 'GLD',   name: 'GoldCoin'},
    {symbol: 'GNT',   name: 'Golem'},
    {symbol: 'GOLOS', name: 'GOLOS'},
    {symbol: 'GRC',   name: 'Gridcoin'},
    {symbol: 'GRS',   name: 'Groestlcoin'},
    {symbol: 'NLG',   name: 'Gulden'},
    {symbol: 'HEAT',  name: 'HEAT'},
    {symbol: 'ICN',   name: 'Iconomi'},
    {symbol: 'INCNT', name: 'INCNT'},
    {symbol: 'IOC',   name: 'IO Coin'},
    {symbol: 'KMD',   name: 'KMD'},
    {symbol: 'KOBO',  name: 'KOBO'},
    {symbol: 'KORE',  name: 'KoreCoin'},
    {symbol: 'LBC',   name: 'LBC'},
    {symbol: 'LTC',   name: 'Litecoin'},
    {symbol: 'LDOGE', name: 'LiteDoge'},
    {symbol: 'MAID',  name: 'MaidSafeCoin'},
    {symbol: 'OMNI',  name: 'Mastercoin (Omni)'},
    {symbol: 'MCO',   name: 'MCO'},
    {symbol: 'MONA',  name: 'MonaCoin'},
    {symbol: 'XMR',   name: 'Monero'},
    {symbol: 'MUE',   name: 'MonetaryUnit'},
    {symbol: 'NMC',   name: 'Namecoin'},
    {symbol: 'XEM',   name: 'NEM'},
    {symbol: 'NEO',   name: 'NEO'},
    {symbol: 'NEOS',  name: 'NeosCoin'},
    {symbol: 'NVC',   name: 'Novacoin'},
    {symbol: 'NBT',   name: 'NuBits'},
    {symbol: 'NXT',   name: 'NXT'},
    {symbol: 'OK',    name: 'OKCash'},
    {symbol: 'OMG',   name: 'OMG'},
    {symbol: 'OPAL',  name: 'OPAL'},
    {symbol: 'PART',  name: 'PART'},
    {symbol: 'PPC',   name: 'Peercoin'},
    {symbol: 'PIVX',  name: 'PIVX'},
    {symbol: 'POT',   name: 'Potcoin'},
    {symbol: 'XPM',   name: 'Primecoin'},
    {symbol: 'QTUM',  name: 'QTUM'},
    {symbol: 'RADS',  name: 'Radium'},
    {symbol: 'RDD',   name: 'Reddcoin'},
    {symbol: 'RBT',   name: 'Rimbit'},
    {symbol: 'XRP',   name: 'Ripple'},
    {symbol: 'RISE',  name: 'RISE'},
    {symbol: 'RBIES', name: 'Rubies'},
    {symbol: 'RBY',   name: 'Rubycoin'},
    {symbol: 'SALT',  name: 'SALT'},
    {symbol: 'SDC',   name: 'ShadowCash'},
    {symbol: 'SLS',   name: 'SLS'},
    {symbol: 'SNRG',  name: 'SNRG'},
    {symbol: 'START', name: 'Startcoin'},
    {symbol: 'STEEM', name: 'Steem'},
    {symbol: 'STR',   name: 'Stellar'},
    {symbol: 'SLG',   name: 'Sterlingcoin'},
    {symbol: 'STRAT', name: 'STRAT'},
    {symbol: 'AMP',   name: 'Synereo'},
    {symbol: 'SYS',   name: 'Syscoin'},
    {symbol: 'TX',    name: 'Transfercoin'},
    {symbol: 'TRIG',  name: 'TRIG'},
    {symbol: 'UBQ',   name: 'UBQ'},
    {symbol: 'XVG',   name: 'Verge'},
    {symbol: 'VRC',   name: 'VeriCoin'},
    {symbol: 'VTC',   name: 'Vertcoin'},
    {symbol: 'VPN',   name: 'VPNCoin'},
    {symbol: 'WAVES', name: 'WAVES'},
    {symbol: 'XBS',   name: 'XBS'},
    {symbol: 'XTZ',   name: 'XTZ'},
    {symbol: 'YBC',   name: 'Ybcoin'},
    {symbol: 'ZEC',   name: 'Zcash'},
    {symbol: 'XZC',   name: 'Zcoin'},
    {symbol: 'ZEIT',  name: 'Zeitcoin'}
  ].freeze

  def up
    CURRENCIES.each do |currency|
      CryptoCurrency.new(
        symbol: currency[:symbol],
        name: currency[:name]
      ).save
    end
  end

  def down
    CryptoCurrency.delete_all
  end
end
